# Exercise 0: Introduction to Python

### Use Python as a calculator to compute 256²

In [3]:
256 * 256

65536

### Put the strings "Hello" and "World!" in two variables. Concatenate both Strings and print them

In [5]:
x = "Hello"
y = "World!"
z = x + y
print(z)

HelloWorld!


### Create a list that contains the 4 strings "alpha", "beta", "gamma", and "delta". Add "epsilon" to the end of this list

In [6]:
arr = ["alpha", "beta", "gamma", "delta"]
arr.append("epsilon")
arr

['alpha', 'beta', 'gamma', 'delta', 'epsilon']

### Create a sublist with the first three elements of this list


In [10]:
arr[:3]

['alpha', 'beta', 'gamma']

### Write a Python program to construct the following pattern using for loops

In [18]:
"""
* 
* * 
* * * 
* * * * 
* * * * * 
* * * * 
* * * 
* * 
*
"""

'\n* \n* * \n* * * \n* * * * \n* * * * * \n* * * * \n* * * \n* * \n*\n'

In [14]:
for i in range(-4, 5, 1):
  x = " ".join(["*" for _ in range(5 - abs(i))])
  print(x)

*
* *
* * *
* * * *
* * * * *
* * * *
* * *
* *
*


### Write a function that takes 3 input parameters and returns the product of these values

In [15]:
def product(x, y, z):
  return x * y * z
product(2, 3, 4)

24

### Write a Python function that takes an int as a parameter and checks if the number is prime or not.

In [16]:
def is_prime(x: int) -> bool:
  for i in range(2, x):
    if x % i == 0:
      return False
  return True

### Use your function to create a list that contains all primes from 2 to 100

In [17]:
[x for x in range(2, 100) if is_prime(x)]

[2,
 3,
 5,
 7,
 11,
 13,
 17,
 19,
 23,
 29,
 31,
 37,
 41,
 43,
 47,
 53,
 59,
 61,
 67,
 71,
 73,
 79,
 83,
 89,
 97]

### Write a function that simulates dice rolls (6-sided dices)
- Write a function that has the number of dice rolls as the input parameter
- The output is a map with the counts how often each result of a roll (1-6) occurred
- You can use the randomint() function from the random package

In [27]:
# load the random package
import random

def roll(times: int) -> dict:
  counter = dict([(i, 0) for i in range(1, 7)])
  for _ in range(times):
    counter[random.randint(1, 6)] += 1
  return counter

roll(10)

{1: 1, 2: 2, 3: 4, 4: 0, 5: 1, 6: 2}

### Combine two dictionaries by adding values for common keys.
d1 = {'a': 100, 'b': 200, 'c':300}

d2 = {'a': 300, 'b': 200, 'd':400}

Sample output: {'a': 400, 'b': 400, 'd': 400, 'c': 300}

In [28]:
def merge_dict(x: dict, y: dict):
  r = x.copy()
  for k, v in y.items():
    r[k] = v + r.get(k, 0)
  return r

merge_dict({'a': 100, 'b': 200, 'c':300}, {'a': 300, 'b': 200, 'd':400})

{'a': 400, 'b': 400, 'c': 300, 'd': 400}

### Create a list of lists. Then, write a list comprehension that creates a list with the lengths of each (sub)list in the primary list

In [29]:
x = [[1,2,3], [4,5], [], [6,7,8,9]]
[len(a) for a in x]

[3, 2, 0, 4]

### Exceptions

Write your own function *my_division* that gets two variables a and b and returns a divided by b. Catch the ZeroDivisionError that occurs if b equals 0 and return 1 in this case.

How could the same behavior be achieved without catching an exception?

In [34]:
def my_division(a, b) -> float:
  try:
    return a / b
  except ZeroDivisionError:
    return 1.0

print(my_division(4, 2))
print(my_division(1, 0))

2.0
1.0


### File handling

Write a function that gets a letter and the path to a (text-)file on your harddrive as input parameters and computes a list as its output. The list should contain one number for each line. The i-th line shows, how often the given letter occurs in line number i in the text file. Test your function on "ftest.txt", which was provided in this exercise!

In [35]:
def count_character(letter: str, path: str):
  with open(path, 'r') as f:
    lines = f.readlines()
    return [sum([1 for c in line if c == letter]) for line in lines]

count_character('a', 'ftest.txt')


[1, 1, 2, 2, 1]

### Change please!
In our currency, we have coins with certain values, e.g., (200,100,50,20,10,5,2,1) cents. Write a function that computes the different options to pay a certain amount X with the given set of coins.

In [47]:
def pay_options(
    price: int,
    changes: list[int],
    current_amount: int = 0,
    index: int = 0,
    options: list[int] = [],
):
    if current_amount == price:
        print([option for option in options])
    elif current_amount > price:
        return
    for i in range(index, len(changes)):
        change = changes[i]
        options.append(change)
        pay_options(price, changes, current_amount + change, i, options)
        options.pop()


pay_options(10, [200, 100, 50, 20, 10, 5, 2, 1])

[10]
[5, 5]
[5, 2, 2, 1]
[5, 2, 1, 1, 1]
[5, 1, 1, 1, 1, 1]
[2, 2, 2, 2, 2]
[2, 2, 2, 2, 1, 1]
[2, 2, 2, 1, 1, 1, 1]
[2, 2, 1, 1, 1, 1, 1, 1]
[2, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


## Numpy

In this last set of tasks, you will have to work with numpy, the the fundamental package for scientific computing with Python.
Make sure to execute the cell below to import the package, we will usually use the abbreviation np for numpy to obtain shorter code.

In [48]:
import numpy as np

### Create a numpy array with 20 rows and 10 columns, where all values are set to zero

In [49]:
np.zeros((20, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### Create an array with the same shape containing all natural numbers 0-199

In [51]:
np.arange(0, 200).reshape(20, 10)

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169

### Create a 4-dimensional array with exactly 16 elements and set all values to a random integer smaller than 5

In [54]:
arr = np.random.randint(0, 5, size=16).reshape(4, 4)
arr

array([[2, 0, 1, 4],
       [0, 2, 2, 4],
       [2, 2, 0, 1],
       [1, 3, 4, 0]])

### What is the mean of all values contained in this array?

In [55]:
np.mean(arr)

1.75

### Select a sub-array containing exactly two elements of that array!

In [57]:
arr[0, 0:2]

array([2, 0])

### Given a numpy array, return a new numpy array that contains only the elements that are greater than 100

In [60]:
arr2 = np.arange(0, 200).reshape(20, 10)
print(arr2)
arr2[arr2 > 100]

[[  0   1   2   3   4   5   6   7   8   9]
 [ 10  11  12  13  14  15  16  17  18  19]
 [ 20  21  22  23  24  25  26  27  28  29]
 [ 30  31  32  33  34  35  36  37  38  39]
 [ 40  41  42  43  44  45  46  47  48  49]
 [ 50  51  52  53  54  55  56  57  58  59]
 [ 60  61  62  63  64  65  66  67  68  69]
 [ 70  71  72  73  74  75  76  77  78  79]
 [ 80  81  82  83  84  85  86  87  88  89]
 [ 90  91  92  93  94  95  96  97  98  99]
 [100 101 102 103 104 105 106 107 108 109]
 [110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129]
 [130 131 132 133 134 135 136 137 138 139]
 [140 141 142 143 144 145 146 147 148 149]
 [150 151 152 153 154 155 156 157 158 159]
 [160 161 162 163 164 165 166 167 168 169]
 [170 171 172 173 174 175 176 177 178 179]
 [180 181 182 183 184 185 186 187 188 189]
 [190 191 192 193 194 195 196 197 198 199]]


array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
       114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126,
       127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
       140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152,
       153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165,
       166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178,
       179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191,
       192, 193, 194, 195, 196, 197, 198, 199])